---
title: "Analyze data using ArchR"
author: "Zhijian Li"
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(stringr)
library(magrittr)
library(WriteXLS)
library(tidyr)
library(dplyr)
library(plotly)
library(cluster)
library(cowplot)
library(gridExtra)
library(viridis)
library(GenomicRanges)
library(GenomeInfoDb)
library(data.table)
library(ArchR)
```

```{r set_parameters, echo=FALSE}
## set parameters
set.seed(42)
addArchRThreads(threads = 1)
addArchRGenome("hg38")
```

## Reading barcodes
```{r}
message("Reading in integrated data...")
heart.integrated <- readRDS("../../ATAC_Integration/data/heart.integrated.Rds")
meta_data <- heart.integrated@meta.data
print(colnames(meta_data))

fib_meta_data <- subset(meta_data, celltype %in% c("Fibroblasts 0",
                                                   "Fibroblasts 1",
                                                   "Fibroblasts 2",
                                                   "Fibroblasts 3",
                                                   "Fibroblasts 5"))


```


## Creating Arrow Files
```{r}
inputFiles <- c("Heart" = "../../Aggregation/Heart/outs/fragments.tsv.gz")

minTSS <- 1
minFrags <- 100

ArrowFiles <- createArrowFiles(
  inputFiles = inputFiles,
  sampleNames = names(inputFiles),
  outputNames = names(inputFiles),
  validBarcodes = rownames(fib_meta_data),
  minTSS = minTSS, 
  minFrags = minFrags, 
  maxFrags = 1e+07,
  QCDir = "QualityControl",
  addTileMat = TRUE,
  addGeneScoreMat = TRUE
)

ArrowFiles
```


## Session information
```{r}
sessionInfo()
```
