---
title: "Quality check"
author: "Zhijian Li"
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(stringr)
library(magrittr)
library(readr)
library(tidyr)
library(dplyr)
library(plotly)
library(Signac)
library(Seurat)
library(cluster)
library(mclust)
library(cowplot)
library(gridExtra)
```

## Load the aggreated data and statistics for each sample

```{r loaddata, echo=FALSE}
# peak-barcode count matrix
counts <- Read10X_h5("../../Aggregation/Heart/outs/filtered_peak_bc_matrix.h5")
metadata <- read.csv(file = "../../Aggregation/Heart/outs/singlecell.csv",
                     header = TRUE, row.names = 1)

# convert some features to log scale
metadata$TSS_fragments_log <- log10(metadata$TSS_fragments + 1)
metadata$DNase_sensitive_region_fragments_log <- log10(metadata$DNase_sensitive_region_fragments + 1)
metadata$enhancer_region_fragments_log <- log10(metadata$enhancer_region_fragments + 1)
metadata$promoter_region_fragments_log <- log10(metadata$promoter_region_fragments + 1)
metadata$on_target_fragments_log <- log10(metadata$on_target_fragments + 1)
metadata$blacklist_region_fragments_log <- log10(metadata$blacklist_region_fragments + 1)
metadata$peak_region_fragments_log <- log10(metadata$peak_region_fragments + 1)
metadata$peak_region_cutsites_log <- log10(metadata$peak_region_cutsites + 1)
metadata$passed_filters_log <- log10(metadata$passed_filters + 1)
metadata$duplicate_log <- log10(metadata$duplicate + 1)

heart <- CreateSeuratObject(counts = counts, assay = 'Peaks',
                            project = 'ATAC', min.cells = 50,
                            names.field = 2, names.delim = "-",
                            meta.data = metadata)

heart <- subset(heart, subset = passed_filters > 3000)
print(dim(heart))

heart$nCount_Peaks_log <- log10(heart$nCount_Peaks + 1)
heart$nFeature_Peaks_log <- log10(heart$nFeature_Peaks + 1)

fragment.path <- "../../Aggregation/Heart/outs/fragments.tsv.gz"
heart <- SetFragments(object = heart, file = fragment.path)

heart <- NucleosomeSignal(object = heart)
heart$pct_reads_in_peaks <- heart$peak_region_fragments / heart$passed_filters * 100
heart$pct_reads_in_promoters <- heart$promoter_region_fragments / heart$passed_filters * 100
heart$blacklist_ratio <- heart$blacklist_region_fragments / heart$peak_region_fragments
```

## add identity
```{r}
heart <- RenameIdents(object = heart, 
                      '1' = 'CK166', 
                      '2' = 'CK167',
                      '3' = 'CK168',
                      '4' = 'CK170',
                      '5' = 'CK171',
                      '6' = 'CK173',
                      '7' = 'CK174')

heart[["patient.ident"]] <- Idents(heart)

heart <- RenameIdents(object = heart, 
                      'CK166' = 'P1_RZ', 
                      'CK167' = 'P5_CR',
                      'CK168' = 'P3_BZ',
                      'CK170' = 'P4_CR',
                      'CK171' = 'P2_BZ',
                      'CK173' = 'P3_RZ',
                      'CK174' = 'P2_IZ')

heart[["spatial.ident"]] <- Idents(heart)

cols.use <- c("P1_RZ" = "#e41a1c",
              "P5_CR" = "#377eb8",
              "P3_BZ" = "#4daf4a",
              "P4_CR" = "#ff7f00",
              "P2_BZ" = "#ffff33",
              "P3_RZ" = "#a65628",
              "P2_IZ" = "#f781bf")

```

## check data quality per patient

```{r, echo=FALSE, fig.height=6, fig.width=16}
p1 <- VlnPlot(object = heart, features = 'TSS_fragments', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p2 <- VlnPlot(object = heart, features = 'DNase_sensitive_region_fragments', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p3 <- VlnPlot(object = heart, features = 'enhancer_region_fragments', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p4 <- VlnPlot(object = heart, features = 'promoter_region_fragments', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p5 <- VlnPlot(object = heart, features = 'on_target_fragments', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p6 <- VlnPlot(object = heart, features = 'blacklist_region_fragments', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p7 <- VlnPlot(object = heart, features = 'peak_region_fragments', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p8 <- VlnPlot(object = heart, features = 'peak_region_cutsites', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p9 <- VlnPlot(object = heart, features = 'passed_filters', 
              pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p10 <- VlnPlot(object = heart, features = 'duplicate', 
               pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p11 <- VlnPlot(object = heart, features = 'pct_reads_in_peaks', 
               pt.size = 0, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p12 <- VlnPlot(object = heart, features = 'pct_reads_in_promoters', 
               pt.size = 0, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p13 <- VlnPlot(object = heart, features = 'blacklist_ratio', 
               pt.size = 0, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p14 <- VlnPlot(object = heart, features = 'nucleosome_signal', 
               pt.size = 0, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p15 <- VlnPlot(object = heart, features = 'nCount_Peaks', 
               pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p16 <- VlnPlot(object = heart, features = 'nFeature_Peaks', 
               pt.size = 0, log = TRUE, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p17 <- FeatureScatter(heart, "peak_region_fragments", "nucleosome_signal", 
                      pt.size = 0, group.by = "spatial.ident", cols = cols.use) + NoLegend()

p18 <- FeatureScatter(heart,"peak_region_fragments", "blacklist_ratio", 
                      pt.size = 0, group.by = "spatial.ident", cols = cols.use) + NoLegend()


CombinePlots(plots = list(p1, p2), ncol = 2)
CombinePlots(plots = list(p3, p4), ncol = 2)
CombinePlots(plots = list(p5, p6), ncol = 2)
CombinePlots(plots = list(p7, p8), ncol = 2)
CombinePlots(plots = list(p9, p10), ncol = 2)
CombinePlots(plots = list(p11, p12), ncol = 2)
CombinePlots(plots = list(p13, p14), ncol = 2)
CombinePlots(plots = list(p15, p16), ncol = 2)
CombinePlots(plots = list(p17, p18), ncol = 2)
```


## save data
```{r}
saveRDS(heart, file = "../data/heart.Rds")
```

## Session information
```{r}
sessionInfo()
```
